name: Build

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [ published ]

env:
  HUSKY: 0

permissions:
  contents: write
  packages: write

jobs:
  metadata:
    name: Get metadata
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Version
        id: version
        run: |
          if ${{ startsWith(github.ref, 'refs/tags/') }}; then
            echo "version=$(git describe --tags `git rev-list --tags --max-count=1`)" >> "$GITHUB_OUTPUT"
          else
            echo "version=devel" >> "$GITHUB_OUTPUT"
          fi

  build:
    name: Build application
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Run build
        run: |
          pnpm i
          pnpm run build

      - name: Archive dist
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: application-build
          path: |
            api/dist
            app/dist
          retention-days: 1

  publish:
    name: Publish results
    runs-on: ubuntu-22.04
    needs:
      - build
      - metadata
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: application-build
          path: ${{ github.workspace }}

      - name: Check presence of dist
        run: |
          ls api/dist
          ls app/dist

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 #v3.10.0

      - name: Build and push
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 #v6.17.0
        with:
          context: .
          push: true
          tags: "ghcr.io/daydream-minecraft/web-monitor:latest,ghcr.io/daydream-minecraft/web-monitor:${{ needs.metadata.outputs.version }}"